### ISSUE TITLE
There is no *.bat files for manual compilation and execution

### ISSUE THREAD

**Issue by dgroup** [Lec1k/task-manager#3]
According to [email rules](http://moodle.sumdu.edu.ua/mod/page/view.php?id=35) your project should contain at least 3 files:
- compile.bat > Compile *.java source to *.class
- build.bat > Package *.class-es into *.jar
- run.bat > Allows to run your application

**Comment by alexey-voronenko** [comment]
Added .bat files to compile,build and run.
